spring:
  application:
    name: service1

server:
  port: 9000

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/