version: "3"
services:
  
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    
    ports:
      - "8761:8761"
    restart: on-failure

  service_1:
    build:
      context: ./service 1
      dockerfile: Dockerfile
    ports:
    - "9001:9001"
    restart: on-failure

  service_2:
    build:
      context: ./Service 2
      dockerfile: Dockerfile

  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
    - "8080:8080"