spring:
  application:
    name: zuul-server

server:
  port: 8080


logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

zuul:
  routes:
    test:
      path: /test/**
      url: https://google.com
    HELLO-CLIENT:
      path: /service1/**
      serviceId : HELLO
    HELLO-CLIENT-1:
      path: /service2/**
      serviceId: HELLO-CLIENT-1
